### ISSUE TITLE
Logo design

### ISSUE THREAD

**Issue by nunojesus** [substack/code-music-studio#10]
Hi,
I have read your work so I decided to creat a logo for you. I hope you like it and you want to use it. I can give you all the formats of the design free. If you want to make changes please specify.

I used the colours of your website.

Greetings

![algo](https://user-images.githubusercontent.com/34600369/39490606-4ddcbbde-4d81-11e8-9972-2315d0e0950a.png)

**Comment by matthiasbeyer** [comment]
Beware: this user opened issues like this on a number of repos. Even with the exact same graphics. Might be scam.

**Comment by nunojesus** [comment]
It´s not a scam dont worry, if you want the logo I will do it, if you dont want just say no and close this issue.

I contribute to many projects with logo designs, this it will just one more or not.

greetings

**Comment by nunojesus** [comment]
You can see here 2 of my logo contributions, and you can see in the Readme file my name as logo designer:

https://github.com/nityanandagohain/SoundHaven
https://github.com/MarxSoul55/cats_vs_dogs

Greetings
Nuno
